### ISSUE TITLE
Command todo list

### ISSUE THREAD

**Issue by lol768** [DSH105/Nexus#41]
- [ ] DBO related commands
  - [ ] Slug -> Curse ID
  - [ ] Curse ID -> slug
  - [ ] General plugin info
- [ ] Bukkit related commands
  - [ ] DLB [API](http://dl.bukkit.org/about/) use 
    - [ ] Latest build info
    - [ ] Ability to lookup a build
- [x] Random-number commands
  - [x] Coin flipper
  - [x] Dice roller
  - [x] Simple number generator (specify min/max)
- [x] Weather command
- [ ] BTC lookup command (similar to DOGE)
- [ ] Subreddit info command
  - [ ] Number of subscribers
  - [ ] List of mods
  - [ ] Is default?
- [ ] Travis support
- [ ] Time command 
  - [ ] Maybe add TZ support
- [ ] Channel management tools
  - [ ] Tempban/kick/permaban etc for voiced users if enabled in channel

PRs appreciated! If you like the look of one of these, give it a go :rocket:

**Comment by DSH105** [comment]
\o/

**Comment by JOPHESTUS** [comment]
shh, willie might coincidentally add all these features all of a sudden

**Comment by DSH105** [comment]
@lol768 Don't forget Travis support too ;)

**Comment by lol768** [comment]
@JOPHESTUS 

Let's be constructive :smiley: 

@DSH105 

Added - more details would be nice :heart:

**Comment by DSH105** [comment]
Will do once I look at the API docs :3

**Comment by stuntguy3000** [comment]
Working on Random(.org's API)

**Comment by lol768** [comment]
Awesome :smile:. Maybe a way to switch between true randomness/pseudorandomness?

**Comment by stuntguy3000** [comment]
https://api.random.org/json-rpc/1/introduction - I'll be fine.

**Comment by JOPHESTUS** [comment]
I shall work on a weather command, yer

**Comment by lol768** [comment]
Ticked off weather command! Thanks @JOPHESTUS :heart:

**Comment by JOPHESTUS** [comment]
np @lol768 
![](https://assets-cdn.github.com/images/icons/emoji/heart.png)

**Comment by lol768** [comment]
@JOPHESTUS Added BTC! Maybe you wanna give it a shot? :)

**Comment by JOPHESTUS** [comment]
@lol768 maybs
